server:
  port: 7002
  servlet:
#    context-path: /eureka/
spring:
  application:
    name: mustang-eureka
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7002
#    prefer-ip-address: true
    instance-id: eureka-7002
    appname: eurekaservice
  client:
    #向注册中心注册自己。 单机情况false
    register-with-eureka: true
    #是否需要去检索服务、单机情况只负责维护实例设置为false
    fetch-registry: true
    serviceurl:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://admin:admin@eureka7001:7001/eureka/,http://admin:admin@eureka7003:7003/eureka/



